// Unified fonts configuration for testing
// Format:
// - type: 'google' or 'adobe'
// - name: Display name for screenshots
// - url: Font URL (for reference)
// - For Google: url will be parsed to get font family
// - For Adobe: id is required for API, slug is extracted from url for CSS

export const FONTS_TO_TEST = [
  { type: 'adobe', name: 'BIZ UDPGothic', url: 'https://fonts.adobe.com/fonts/biz-udpgothic', id: 'biz-udpgothic' },
  { type: 'adobe', name: 'Laca Variable', url: 'https://fonts.adobe.com/fonts/laca-variable', id: 'laca-variable' },
  { type: 'adobe', name: 'Laca Text Variable', url: 'https://fonts.adobe.com/fonts/laca-text-variable', id: 'laca-text-variable' },
  { type: 'adobe', name: 'Superblue', url: 'https://fonts.adobe.com/fonts/superblue', id: 'superblue' },
  { type: 'adobe', name: 'Marseille', url: 'https://fonts.adobe.com/fonts/marseille', id: 'marseille' },
  { type: 'adobe', name: 'Karol', url: 'https://fonts.adobe.com/fonts/karol', id: 'karol' },
  { type: 'adobe', name: 'Goldich', url: 'https://fonts.adobe.com/fonts/goldich', id: 'goldich' },
  { type: 'adobe', name: 'Bonnie', url: 'https://fonts.adobe.com/fonts/bonnie', id: 'bonnie' },
  { type: 'adobe', name: 'Directa Serif Variable', url: 'https://fonts.adobe.com/fonts/directa-serif-variable', id: 'directa-serif-variable' },
  { type: 'adobe', name: 'Gowun Dodum', url: 'https://fonts.adobe.com/fonts/gowun-dodum', id: 'gowun-dodum' },
  { type: 'adobe', name: 'Indivisible Variable', url: 'https://fonts.adobe.com/fonts/indivisible-variable', id: 'indivisible-variable' },
  { type: 'adobe', name: 'Objektiv Variable', url: 'https://fonts.adobe.com/fonts/objektiv-variable', id: 'objektiv-variable' },
  { type: 'adobe', name: 'Highgate Variable', url: 'https://fonts.adobe.com/fonts/highgate-variable', id: 'highgate-variable' },
  { type: 'adobe', name: 'Gal Gothic Variable', url: 'https://fonts.adobe.com/fonts/gal-gothic-variable', id: 'gal-gothic-variable' },
  { type: 'adobe', name: 'Sculpin Variable', url: 'https://fonts.adobe.com/fonts/sculpin-variable', id: 'sculpin-variable' },
  { type: 'adobe', name: 'Study Variable', url: 'https://fonts.adobe.com/fonts/study-variable', id: 'study-variable' },
  { type: 'adobe', name: 'Normalidad Variable', url: 'https://fonts.adobe.com/fonts/normalidad-variable', id: 'normalidad-variable' },
  { type: 'adobe', name: 'Adapt Variable', url: 'https://fonts.adobe.com/fonts/adapt-variable', id: 'adapt-variable' },
  { type: 'adobe', name: 'Auster Variable', url: 'https://fonts.adobe.com/fonts/auster-variable', id: 'auster-variable' },
  { type: 'adobe', name: 'DIN 2014 Rounded Variable', url: 'https://fonts.adobe.com/fonts/din-2014-rounded-variable', id: 'din-2014-rounded-variable' },
  { type: 'adobe', name: 'Carbona Variable', url: 'https://fonts.adobe.com/fonts/carbona-variable', id: 'carbona-variable' },
  { type: 'adobe', name: 'Fact Variable', url: 'https://fonts.adobe.com/fonts/fact-variable', id: 'fact-variable' },
  { type: 'adobe', name: 'Gate A1 Variable', url: 'https://fonts.adobe.com/fonts/gate-a1-variable', id: 'gate-a1-variable' },
  { type: 'adobe', name: 'Kumbh Sans Variable', url: 'https://fonts.adobe.com/fonts/kumbh-sans-variable', id: 'kumbh-sans-variable' },
  { type: 'adobe', name: 'Exo 2 Variable', url: 'https://fonts.adobe.com/fonts/exo-2-variable', id: 'exo-2-variable' },
  { type: 'adobe', name: 'Mulish Variable', url: 'https://fonts.adobe.com/fonts/mulish-variable', id: 'mulish-variable' },
  { type: 'adobe', name: 'Allotrope Variable', url: 'https://fonts.adobe.com/fonts/allotrope-variable', id: 'allotrope-variable' },
  { type: 'adobe', name: 'Bouba Round Variable', url: 'https://fonts.adobe.com/fonts/bouba-round-variable', id: 'bouba-round-variable' },
  { type: 'adobe', name: 'Oook Variable', url: 'https://fonts.adobe.com/fonts/oook-variable', id: 'oook-variable' },
  { type: 'adobe', name: 'Seitu Variable', url: 'https://fonts.adobe.com/fonts/seitu-variable', id: 'seitu-variable' },
  { type: 'adobe', name: 'Tome Sans Variable', url: 'https://fonts.adobe.com/fonts/tome-sans-variable', id: 'tome-sans-variable' },
  { type: 'adobe', name: 'Nextexit Variable', url: 'https://fonts.adobe.com/fonts/nextexit-variable', id: 'nextexit-variable' },
  { type: 'adobe', name: 'Myriad Variable', url: 'https://fonts.adobe.com/fonts/myriad-variable', id: 'myriad-variable' },
  { type: 'adobe', name: 'Source Sans 3 Variable', url: 'https://fonts.adobe.com/fonts/source-sans-3-variable', id: 'source-sans-3-variable' },
  { type: 'adobe', name: 'Pelago Variable', url: 'https://fonts.adobe.com/fonts/pelago-variable', id: 'pelago-variable' },
  { type: 'adobe', name: 'Narkiss Text Variable', url: 'https://fonts.adobe.com/fonts/narkiss-text-variable', id: 'narkiss-text-variable' },
  { type: 'adobe', name: 'Zedou', url: 'https://fonts.adobe.com/fonts/zedou', id: 'zedou' },
  { type: 'adobe', name: 'Bakemono Variable', url: 'https://fonts.adobe.com/fonts/bakemono-variable', id: 'bakemono-variable' },
  { type: 'adobe', name: 'Narkiss Tam', url: 'https://fonts.adobe.com/fonts/narkiss-tam', id: 'narkiss-tam' },
  { type: 'adobe', name: 'Liebling', url: 'https://fonts.adobe.com/fonts/liebling', id: 'liebling' },
  { type: 'adobe', name: 'Karol Sans', url: 'https://fonts.adobe.com/fonts/karol-sans', id: 'karol-sans' },
  { type: 'adobe', name: 'Gelica', url: 'https://fonts.adobe.com/fonts/gelica', id: 'gelica' },
  { type: 'adobe', name: 'Dejanire Text', url: 'https://fonts.adobe.com/fonts/dejanire-text', id: 'dejanire-text' },
  { type: 'adobe', name: 'Area', url: 'https://fonts.adobe.com/fonts/area', id: 'area' },
  { type: 'adobe', name: 'Kim Jung Chul Myungjo', url: 'https://fonts.adobe.com/fonts/kim-jung-chul-myungjo', id: 'kim-jung-chul-myungjo' },
  { type: 'adobe', name: 'Effra CC', url: 'https://fonts.adobe.com/fonts/effra-cc', id: 'effra-cc' },
  { type: 'adobe', name: 'Darkmode CC', url: 'https://fonts.adobe.com/fonts/darkmode-cc', id: 'darkmode-cc' },
  { type: 'adobe', name: 'Narkissim', url: 'https://fonts.adobe.com/fonts/narkissim', id: 'narkissim' },
  { type: 'adobe', name: 'Redonda', url: 'https://fonts.adobe.com/fonts/redonda', id: 'redonda' },
  { type: 'adobe', name: 'Proxima Sera', url: 'https://fonts.adobe.com/fonts/proxima-sera', id: 'proxima-sera' },
  { type: 'adobe', name: 'Raritas', url: 'https://fonts.adobe.com/fonts/raritas', id: 'raritas' },
  { type: 'adobe', name: 'Fagun', url: 'https://fonts.adobe.com/fonts/fagun', id: 'fagun' },
  { type: 'adobe', name: 'Greycliff CF', url: 'https://fonts.adobe.com/fonts/greycliff-cf', id: 'greycliff-cf' },
  { type: 'adobe', name: 'MVB Salis', url: 'https://fonts.adobe.com/fonts/mvb-salis', id: 'mvb-salis' },
  { type: 'adobe', name: 'New Atten Round', url: 'https://fonts.adobe.com/fonts/new-atten-round', id: 'new-atten-round' },
  { type: 'adobe', name: 'New Atten', url: 'https://fonts.adobe.com/fonts/new-atten', id: 'new-atten' },
  { type: 'adobe', name: 'New Rubrik Edge', url: 'https://fonts.adobe.com/fonts/new-rubrik-edge', id: 'new-rubrik-edge' },
  { type: 'adobe', name: 'New Reason', url: 'https://fonts.adobe.com/fonts/new-reason', id: 'new-reason' },
  { type: 'adobe', name: 'New Hero', url: 'https://fonts.adobe.com/fonts/new-hero', id: 'new-hero' },
  { type: 'adobe', name: 'Frank New', url: 'https://fonts.adobe.com/fonts/frank-new', id: 'frank-new' },
  { type: 'adobe', name: 'Goodchild Pro', url: 'https://fonts.adobe.com/fonts/goodchild-pro', id: 'goodchild-pro' },
  { type: 'adobe', name: 'Gotu', url: 'https://fonts.adobe.com/fonts/gotu', id: 'gotu' },
  { type: 'adobe', name: 'Hanken Grotesk', url: 'https://fonts.adobe.com/fonts/hanken-grotesk', id: 'hanken-grotesk' },
  { type: 'adobe', name: 'Hind Vadodara', url: 'https://fonts.adobe.com/fonts/hind-vadodara', id: 'hind-vadodara' },
  { type: 'adobe', name: 'Inknut Antiqua', url: 'https://fonts.adobe.com/fonts/inknut-antiqua', id: 'inknut-antiqua' },
  { type: 'adobe', name: 'Inria Sans', url: 'https://fonts.adobe.com/fonts/inria-sans', id: 'inria-sans' },
  { type: 'adobe', name: 'Instrument Sans Variable', url: 'https://fonts.adobe.com/fonts/instrument-sans-variable', id: 'instrument-sans-variable' },
  { type: 'adobe', name: 'K2D', url: 'https://fonts.adobe.com/fonts/k2d', id: 'k2d' },
  { type: 'adobe', name: 'Oxanium', url: 'https://fonts.adobe.com/fonts/oxanium', id: 'oxanium' },
  { type: 'adobe', name: 'Spectral', url: 'https://fonts.adobe.com/fonts/spectral', id: 'spectral' },
  { type: 'adobe', name: 'Halant', url: 'https://fonts.adobe.com/fonts/halant', id: 'halant' },
  { type: 'adobe', name: 'Pracharath', url: 'https://fonts.adobe.com/fonts/pracharath', id: 'pracharath' },
  { type: 'adobe', name: 'Preuksa', url: 'https://fonts.adobe.com/fonts/preuksa', id: 'preuksa' },
  { type: 'adobe', name: 'Deuterium Variable', url: 'https://fonts.adobe.com/fonts/deuterium-variable', id: 'deuterium-variable' },
  { type: 'adobe', name: 'Peridot Devanagari', url: 'https://fonts.adobe.com/fonts/peridot-devanagari', id: 'peridot-devanagari' },
  { type: 'adobe', name: 'Gamay Variable', url: 'https://fonts.adobe.com/fonts/gamay-variable', id: 'gamay-variable' },
  { type: 'adobe', name: 'Noto Serif Devanagari', url: 'https://fonts.adobe.com/fonts/noto-serif-devanagari', id: 'noto-serif-devanagari' },
  { type: 'adobe', name: 'Baloo Bhai 2', url: 'https://fonts.adobe.com/fonts/baloo-bhai-2', id: 'baloo-bhai-2' },
  { type: 'adobe', name: 'DM Sans', url: 'https://fonts.adobe.com/fonts/dm-sans', id: 'dm-sans' },
  { type: 'adobe', name: 'JAF Cupidus', url: 'https://fonts.adobe.com/fonts/jaf-cupidus', id: 'jaf-cupidus' },
  { type: 'adobe', name: 'Murecho', url: 'https://fonts.adobe.com/fonts/murecho', id: 'murecho' },
  { type: 'adobe', name: 'Neutronic', url: 'https://fonts.adobe.com/fonts/neutronic', id: 'neutronic' },
  { type: 'adobe', name: 'Le Havre Rounded', url: 'https://fonts.adobe.com/fonts/le-havre-rounded', id: 'le-havre-rounded' },
  { type: 'adobe', name: 'Sofia Soft', url: 'https://fonts.adobe.com/fonts/sofia-soft', id: 'sofia-soft' },
  { type: 'adobe', name: 'Sole Sans Variable', url: 'https://fonts.adobe.com/fonts/sole-sans-variable', id: 'sole-sans-variable' },
  { type: 'adobe', name: 'Scala Sans', url: 'https://fonts.adobe.com/fonts/scala-sans', id: 'scala-sans' },
  { type: 'adobe', name: 'Utility Pro', url: 'https://fonts.adobe.com/fonts/utility-pro', id: 'utility-pro' },
  { type: 'adobe', name: 'Area Variable', url: 'https://fonts.adobe.com/fonts/area-variable', id: 'area-variable' },
  { type: 'adobe', name: 'Jali Latin Variable', url: 'https://fonts.adobe.com/fonts/jali-latin-variable', id: 'jali-latin-variable' },
  { type: 'adobe', name: 'Portada Thai Variable', url: 'https://fonts.adobe.com/fonts/portada-thai-variable', id: 'portada-thai-variable' },
  { type: 'adobe', name: 'Nexus Sans', url: 'https://fonts.adobe.com/fonts/nexus-sans', id: 'nexus-sans' },
  { type: 'adobe', name: 'Newnord', url: 'https://fonts.adobe.com/fonts/newnord', id: 'newnord' },
  { type: 'adobe', name: 'Enra Semi Variable', url: 'https://fonts.adobe.com/fonts/enra-semi-variable', id: 'enra-semi-variable' },
  { type: 'adobe', name: 'Enra Sans Variable', url: 'https://fonts.adobe.com/fonts/enra-sans-variable', id: 'enra-sans-variable' },
  { type: 'adobe', name: 'Panno Sign', url: 'https://fonts.adobe.com/fonts/panno-sign', id: 'panno-sign' },
  { type: 'adobe', name: 'Guyot Sans', url: 'https://fonts.adobe.com/fonts/guyot-sans', id: 'guyot-sans' },
  { type: 'adobe', name: 'Farnham Text', url: 'https://fonts.adobe.com/fonts/farnham-text', id: 'farnham-text' },
  { type: 'adobe', name: 'Neulis Sans', url: 'https://fonts.adobe.com/fonts/neulis-sans', id: 'neulis-sans' },
  { type: 'adobe', name: 'Neulis Neue', url: 'https://fonts.adobe.com/fonts/neulis-neue', id: 'neulis-neue' },
  { type: 'adobe', name: 'PLN Romanceche', url: 'https://fonts.adobe.com/fonts/pln-romanceche', id: 'pln-romanceche' },
  { type: 'adobe', name: 'Tiffin Devanagari', url: 'https://fonts.adobe.com/fonts/tiffin-devanagari', id: 'tiffin-devanagari' },
  { type: 'adobe', name: 'Kit', url: 'https://fonts.adobe.com/fonts/kit', id: 'kit' },
  { type: 'adobe', name: 'Alfabet', url: 'https://fonts.adobe.com/fonts/alfabet', id: 'alfabet' },
  { type: 'adobe', name: 'Yoon Giraffe Gothic', url: 'https://fonts.adobe.com/fonts/yoon-giraffegothic', id: 'yoon-giraffegothic' },
  { type: 'adobe', name: 'DS Endendend', url: 'https://fonts.adobe.com/fonts/ds-endendend', id: 'ds-endendend' },
  { type: 'adobe', name: 'Ten Mincho Antique', url: 'https://fonts.adobe.com/fonts/ten-mincho-antique', id: 'ten-mincho-antique' },
  { type: 'adobe', name: 'Aktiv Grotesk Georgian', url: 'https://fonts.adobe.com/fonts/aktiv-grotesk-georgian', id: 'aktiv-grotesk-georgian' },
  { type: 'adobe', name: 'Ivyepic Variable', url: 'https://fonts.adobe.com/fonts/ivyepic-variable', id: 'ivyepic-variable' },
  { type: 'adobe', name: 'Archivo Variable', url: 'https://fonts.adobe.com/fonts/archivo-variable', id: 'archivo-variable' },
  { type: 'adobe', name: 'Baloo 2', url: 'https://fonts.adobe.com/fonts/baloo-2', id: 'baloo-2' },
  { type: 'adobe', name: 'Baloo Tamma 2', url: 'https://fonts.adobe.com/fonts/baloo-tamma-2', id: 'baloo-tamma-2' },
  { type: 'adobe', name: 'Cambay', url: 'https://fonts.adobe.com/fonts/cambay', id: 'cambay' },
];
