export const glassEffectConfig = {
  displacementScale: 50,
  aberrationIntensity: 5,
  displacementCurvature: 20,
  glassBlur: 50,
  glassSaturation: 185,
  glassBrightness: 115,
  glassContrast: 118,
  glassTintHue: 210,
  glassTintOpacity: 50,
  refractionDepth: 1.0,
  surfaceReflection: 0.45,
  lightIntensity: 0.75,
  lightSpread: 1.1,
  lightHue: 210,
  shadowDepth: 0.4,
  highlightReflection: 0.45,
  noiseStrength: 0.22,
  noiseRefractionDepth: 2.0,
  outlineIntensity: 0,
  outlineGlassTintHue: 210,
  shaderCornerRadius: 0.2,
  shaderDistortionStart: 0.3,
  shaderDistortionEnd: 0.2,
  shaderDistortionOffset: 0.15,
  shaderScalingStart: 0,
  shaderScalingEnd: 1,
};
