// Glass effect configuration for intro rectangles
export const INTRO_GLASS_CONFIG = {
  displacementScale: 55,
  aberrationIntensity: 4.9,
  displacementCurvature: 1.3,
  glassBlur: 50,
  glassSaturation: 285,
  glassBrightness: 179,
  glassContrast: 120,
  glassTintHue: 132,
  glassTintOpacity: 0,
  refractionDepth: 4,
  surfaceReflection: 0.8,
  shadowDepth: 30,
  lightIntensity: 0.08,
  lightSpread: 1.42,
  lightHue: 210,
  highlightReflection: 0.45,
  noiseStrength: 0.22,
  noiseRefractionDepth: 2.0,
  outlineIntensity: 0,
  outlineGlassTintHue: 210,
  contentFilterOpacity: 1,
  shaderCornerRadius: -0.2,
  shaderRectWidth: 0,
  shaderRectHeight: 0,
  shaderCenterOffsetX: 0,
  shaderCenterOffsetY: 0,
  shaderEdgeSoftness: 1.6,
  shaderDistortionStart: 0.41,
  shaderDistortionEnd: 0.25,
  shaderDistortionOffset: 0.21,
  shaderScalingStart: 0.7,
  shaderScalingEnd: 1,
};
